language: en

# These items should remain in the list to avoid duplication bugs
BlockedItems:
  - "SHULKER_BOX"
  - "WHITE_SHULKER_BOX"
  - "GRAY_SHULKER_BOX"
  - "BLACK_SHULKER_BOX"
  - "BROWN_SHULKER_BOX"
  - "RED_SHULKER_BOX"
  - "ORANGE_SHULKER_BOX"
  - "YELLOW_SHULKER_BOX"
  - "LIME_SHULKER_BOX"
  - "GREEN_SHULKER_BOX"
  - "CYAN_SHULKER_BOX"
  - "LIGHT_BLUE_SHULKER_BOX"
  - "BLUE_SHULKER_BOX"
  - "PURPLE_SHULKER_BOX"
  - "MAGENTA_SHULKER_BOX"
  - "PINK_SHULKER_BOX"
  - "CHEST"
  - "TRAPPED_CHEST"
  - "HOPPER"
  - "ENDER_CHEST"
  - "BARREL"
  - "FURNANCE"