name: VItemSign
version: '1.0.1'
main: de.varilx.vitemsign.VItemSign
loader: de.varilx.vitemsign.loader.VItemSignLoader
api-version: '1.21.5'
author: ShadowDev1929
dependencies:
  server:
    NBTAPI:
      required: true
      load: BEFORE
      join-classpath: true
    LuckPerms:
      required: false
      load: BEFORE
      join-classpath: true
    WorldGuard:
      required: false
      load: BEFORE
      join-classpath: true

